version: "3.9"

services:
  blog_ui:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: ui_container
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://181.215.69.131:44322/api
    ports:
      - "3000:3000"   